In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("filereport.tsv", sep="\t")

In [3]:
df.head()

,run_accession,experiment_accession,library_name,submitted_ftp,sample_title,sample_accession
0,ERR1630013,ERX1700346,AZ_A1_s,ftp.sra.ebi.ac.uk/vol1/run/ERR163/ERR1630013/A...,AZ_A1,SAMEA4437021
1,ERR1630028,ERX1700361,AZ_B12_s,ftp.sra.ebi.ac.uk/vol1/run/ERR163/ERR1630028/A...,AZ_B12,SAMEA4437036
2,ERR1630029,ERX1700362,AZ_B2_s,ftp.sra.ebi.ac.uk/vol1/run/ERR163/ERR1630029/A...,AZ_B2,SAMEA4437037
3,ERR1630034,ERX1700367,AZ_B7_s,ftp.sra.ebi.ac.uk/vol1/run/ERR163/ERR1630034/A...,AZ_B7,SAMEA4437042
4,ERR1630035,ERX1700368,AZ_B8_s,ftp.sra.ebi.ac.uk/vol1/run/ERR163/ERR1630035/A...,AZ_B8,SAMEA4437043

In [4]:
sample_titles = df["sample_title"].to_numpy()

In [5]:
dfID = pd.read_csv("donor_IDs.csv")

In [6]:
donor_IDs = dfID["Donor ID"].to_numpy()

In [7]:
donor_IDs

array(['AZ', 'HP1502401', 'HP1504101T2D', 'HP1504901', 'HP1506401',
       'HP1507101', 'HP1508501T2D', 'HP1509101', 'HP1525301T2D',
       'HP1526901T2D'], dtype=object)

In [8]:
first = sample_titles[0].split("_")[0]

In [9]:
donor_dict = {}
for ID in donor_IDs:
    donor_dict[ID] = 0

In [10]:
for sample_title in sample_titles:
    donor_dict[sample_title.split("_")[0]] += 1

In [11]:
donor_dict

{'AZ': 96,
 'HP1502401': 352,
 'HP1504101T2D': 383,
 'HP1504901': 383,
 'HP1506401': 383,
 'HP1507101': 383,
 'HP1508501T2D': 383,
 'HP1509101': 383,
 'HP1525301T2D': 384,
 'HP1526901T2D': 384}

### Randomly Sample 10 from Each Donor

In [ ]:
chosen_samples = df.iloc[0:0]
chosen_samples

Empty DataFrame
Columns: [run_accession, experiment_accession, library_name, submitted_ftp, sample_title, sample_accession]
Index: []

In [85]:
for donor_ID in donor_IDs:
    mask = df["sample_title"].str.contains(donor_ID)
    donor_samples = df[mask]
    random_samples = donor_samples.sample(n=10, random_state=42)
    chosen_samples = pd.concat([chosen_samples, random_samples], ignore_index=True)

In [86]:
chosen_samples.shape

(100, 6)

In [13]:
#links = chosen_samples["submitted_ftp"].to_numpy()
links = df["submitted_ftp"].to_numpy()

In [15]:
len(links)

3514

### Create shell Script

In [16]:
with open("download_all_fastq.sh", "w", encoding='utf-8') as f:
    for link in links:
        f.write(f"wget -nc ftp://{link}\n")